import turtle
T = turtle.Turtle()
screen = T.getscreen()
screen.bgpic("circles.gif")
T.shape("turtle")
T.speed(1)
T.right(30)
T.forward(70)
T.left(170)
T.forward(190)
T.left(90)
T.forward(150)
turtle.done()
