print("Here's my pet bird!")
print("(o<")
print("/ }")
print (" L")
print("")
print("meet my robot max!")
print(" [@@] ")
print("/|_|\\")
print(" d  b ")
print("meet my fish!")
print("o<")
print("   o<")
print(" o<")
print("meet my owl!")
print("{o,o}")
print("/)_)")
print(" , ,")
print("meet my rabit!")
print(" _     _")
print("( \__/ )")
print("(= '.' =)")
print("('')_('')")
print(":-(")
